# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Agent harness scaffolding for Claude Code"
  homepage "https://github.com/samahlstrom/forge-cli"
  version "0.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.5/forge_0.2.5_darwin_amd64.tar.gz"
      sha256 "a1fccf8a241d5375704a4f753d2b378d57c85e149bddbdadc3b9a4950baf1e7f"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.5/forge_0.2.5_darwin_arm64.tar.gz"
      sha256 "6bf7bae302a314f17deedd7cfa150f5368963d6c290c42e74a4d013c6be9b017"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.5/forge_0.2.5_linux_amd64.tar.gz"
      sha256 "64c49ef5773f42b8cb9e4f2f71f072970eb445dd9273292f63f000fcb5ce2117"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.5/forge_0.2.5_linux_arm64.tar.gz"
      sha256 "57418e8721f749ea2668ef9ef3fab7f89f9fa1423d06b1d1fd0e0fc94a45f7c3"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end
end
