# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Agent harness scaffolding for Claude Code"
  homepage "https://github.com/samahlstrom/forge-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.0/forge_0.2.0_darwin_amd64.tar.gz"
      sha256 "5d2c4d00975774816f0e53a4f971b0269ef171f74e91bddea51c65a11c272fd3"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.0/forge_0.2.0_darwin_arm64.tar.gz"
      sha256 "dd481d54d29227f37a22cd565c1a3c1206167ca71eec91057dca42e01b2e0a14"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.0/forge_0.2.0_linux_amd64.tar.gz"
      sha256 "6fa9b68b191168212addc5417c6838407d9f38cb3f6d3e984afd47bcb1f14be9"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.2.0/forge_0.2.0_linux_arm64.tar.gz"
      sha256 "793e9209435ff6530d670f286afead6cb42b7b12a8f8921daefd1963d55ad10e"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end
end
