# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Portable AI agent toolkit for Claude Code"
  homepage "https://github.com/samahlstrom/forge-cli"
  version "0.3.31"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.3.31/forge_0.3.31_darwin_amd64.tar.gz"
      sha256 "8fae3d8a7824c143047f02e304de7e0d44961eda04817adcf05bef530b4e52a5"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.3.31/forge_0.3.31_darwin_arm64.tar.gz"
      sha256 "51c77b5758ac5a5925d7f36a5a16954159f567ed2b1a85724244b10d84e67ca4"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.3.31/forge_0.3.31_linux_amd64.tar.gz"
      sha256 "96bc135634ce1e31e357f4ba4dfd96c6ae32215edb7dde88df713fc96d01b105"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samahlstrom/forge-cli/releases/download/v0.3.31/forge_0.3.31_linux_arm64.tar.gz"
      sha256 "7dfa8de81900f5206543bb8cdf4f6c56849a35c3b54e7574e9366eb9497f5f69"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end
end
